name: 'Create/destroy runners'
description: 'Github action to create and destroy Runners'
author: 'cellinacywinska & LorenzoDrudi'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  pulumi-config-path: 
    description: 'A path to your Pulumi project config file'
    required: true
    default: ''
  pulumi-goal:  
    description: 'The name of the Pulumi goal. Supported values: create, destroy'
    required: true
    default: ''
  pulumi-stack-name:
    description: 'The name of the Pulumi stack.'
    required: true
    default: ''
  pulumi-cloud-provider:
    description: 'The name of the Pulumi cloud provider. Supported providers: aws, gcp' 
    required: true
    default: ''
  cloud-architecture: 
    description: 'Supported architecture names: amd64 or arm64 (no support for gcp + arm64)' 
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
